[phases.setup]
nixPkgs = ["python312", "postgresql", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install -v --no-cache-dir --prefer-binary -r requirements.txt",
  ". /opt/venv/bin/activate && pip list"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
