[phases.setup]
nixPkgs = ["python311", "pip", "rustc", "cargo"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install --prefer-binary -r requirements.txt"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
